/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TulipAppRouteImport } from './routes/tulip-app'
import { Route as SwiftRateAppRouteImport } from './routes/swift-rate-app'
import { Route as ProfileRouteImport } from './routes/profile'
import { Route as LaurienlaAppRouteImport } from './routes/laurienla-app'
import { Route as GraphicRouteImport } from './routes/graphic'
import { Route as AtmCardRouteImport } from './routes/atm-card'
import { Route as IndexRouteImport } from './routes/index'

const TulipAppRoute = TulipAppRouteImport.update({
  id: '/tulip-app',
  path: '/tulip-app',
  getParentRoute: () => rootRouteImport,
} as any)
const SwiftRateAppRoute = SwiftRateAppRouteImport.update({
  id: '/swift-rate-app',
  path: '/swift-rate-app',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileRoute = ProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const LaurienlaAppRoute = LaurienlaAppRouteImport.update({
  id: '/laurienla-app',
  path: '/laurienla-app',
  getParentRoute: () => rootRouteImport,
} as any)
const GraphicRoute = GraphicRouteImport.update({
  id: '/graphic',
  path: '/graphic',
  getParentRoute: () => rootRouteImport,
} as any)
const AtmCardRoute = AtmCardRouteImport.update({
  id: '/atm-card',
  path: '/atm-card',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/atm-card': typeof AtmCardRoute
  '/graphic': typeof GraphicRoute
  '/laurienla-app': typeof LaurienlaAppRoute
  '/profile': typeof ProfileRoute
  '/swift-rate-app': typeof SwiftRateAppRoute
  '/tulip-app': typeof TulipAppRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/atm-card': typeof AtmCardRoute
  '/graphic': typeof GraphicRoute
  '/laurienla-app': typeof LaurienlaAppRoute
  '/profile': typeof ProfileRoute
  '/swift-rate-app': typeof SwiftRateAppRoute
  '/tulip-app': typeof TulipAppRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/atm-card': typeof AtmCardRoute
  '/graphic': typeof GraphicRoute
  '/laurienla-app': typeof LaurienlaAppRoute
  '/profile': typeof ProfileRoute
  '/swift-rate-app': typeof SwiftRateAppRoute
  '/tulip-app': typeof TulipAppRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/atm-card'
    | '/graphic'
    | '/laurienla-app'
    | '/profile'
    | '/swift-rate-app'
    | '/tulip-app'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/atm-card'
    | '/graphic'
    | '/laurienla-app'
    | '/profile'
    | '/swift-rate-app'
    | '/tulip-app'
  id:
    | '__root__'
    | '/'
    | '/atm-card'
    | '/graphic'
    | '/laurienla-app'
    | '/profile'
    | '/swift-rate-app'
    | '/tulip-app'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AtmCardRoute: typeof AtmCardRoute
  GraphicRoute: typeof GraphicRoute
  LaurienlaAppRoute: typeof LaurienlaAppRoute
  ProfileRoute: typeof ProfileRoute
  SwiftRateAppRoute: typeof SwiftRateAppRoute
  TulipAppRoute: typeof TulipAppRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/tulip-app': {
      id: '/tulip-app'
      path: '/tulip-app'
      fullPath: '/tulip-app'
      preLoaderRoute: typeof TulipAppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/swift-rate-app': {
      id: '/swift-rate-app'
      path: '/swift-rate-app'
      fullPath: '/swift-rate-app'
      preLoaderRoute: typeof SwiftRateAppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile': {
      id: '/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof ProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/laurienla-app': {
      id: '/laurienla-app'
      path: '/laurienla-app'
      fullPath: '/laurienla-app'
      preLoaderRoute: typeof LaurienlaAppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/graphic': {
      id: '/graphic'
      path: '/graphic'
      fullPath: '/graphic'
      preLoaderRoute: typeof GraphicRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/atm-card': {
      id: '/atm-card'
      path: '/atm-card'
      fullPath: '/atm-card'
      preLoaderRoute: typeof AtmCardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AtmCardRoute: AtmCardRoute,
  GraphicRoute: GraphicRoute,
  LaurienlaAppRoute: LaurienlaAppRoute,
  ProfileRoute: ProfileRoute,
  SwiftRateAppRoute: SwiftRateAppRoute,
  TulipAppRoute: TulipAppRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
