/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TulipAppRouteImport } from './routes/tulip-app'
import { Route as SwiftRateAppRouteImport } from './routes/swift-rate-app'
import { Route as ProfileRouteImport } from './routes/profile'
import { Route as LittleLuminariesRouteImport } from './routes/little-luminaries'
import { Route as LaurienlaCakeRouteImport } from './routes/laurienla-cake'
import { Route as IllustrationRouteImport } from './routes/illustration'
import { Route as HeikenmaSolarRouteImport } from './routes/heikenma-solar'
import { Route as AtmCardRouteImport } from './routes/atm-card'
import { Route as IndexRouteImport } from './routes/index'

const TulipAppRoute = TulipAppRouteImport.update({
  id: '/tulip-app',
  path: '/tulip-app',
  getParentRoute: () => rootRouteImport,
} as any)
const SwiftRateAppRoute = SwiftRateAppRouteImport.update({
  id: '/swift-rate-app',
  path: '/swift-rate-app',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileRoute = ProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const LittleLuminariesRoute = LittleLuminariesRouteImport.update({
  id: '/little-luminaries',
  path: '/little-luminaries',
  getParentRoute: () => rootRouteImport,
} as any)
const LaurienlaCakeRoute = LaurienlaCakeRouteImport.update({
  id: '/laurienla-cake',
  path: '/laurienla-cake',
  getParentRoute: () => rootRouteImport,
} as any)
const IllustrationRoute = IllustrationRouteImport.update({
  id: '/illustration',
  path: '/illustration',
  getParentRoute: () => rootRouteImport,
} as any)
const HeikenmaSolarRoute = HeikenmaSolarRouteImport.update({
  id: '/heikenma-solar',
  path: '/heikenma-solar',
  getParentRoute: () => rootRouteImport,
} as any)
const AtmCardRoute = AtmCardRouteImport.update({
  id: '/atm-card',
  path: '/atm-card',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/atm-card': typeof AtmCardRoute
  '/heikenma-solar': typeof HeikenmaSolarRoute
  '/illustration': typeof IllustrationRoute
  '/laurienla-cake': typeof LaurienlaCakeRoute
  '/little-luminaries': typeof LittleLuminariesRoute
  '/profile': typeof ProfileRoute
  '/swift-rate-app': typeof SwiftRateAppRoute
  '/tulip-app': typeof TulipAppRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/atm-card': typeof AtmCardRoute
  '/heikenma-solar': typeof HeikenmaSolarRoute
  '/illustration': typeof IllustrationRoute
  '/laurienla-cake': typeof LaurienlaCakeRoute
  '/little-luminaries': typeof LittleLuminariesRoute
  '/profile': typeof ProfileRoute
  '/swift-rate-app': typeof SwiftRateAppRoute
  '/tulip-app': typeof TulipAppRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/atm-card': typeof AtmCardRoute
  '/heikenma-solar': typeof HeikenmaSolarRoute
  '/illustration': typeof IllustrationRoute
  '/laurienla-cake': typeof LaurienlaCakeRoute
  '/little-luminaries': typeof LittleLuminariesRoute
  '/profile': typeof ProfileRoute
  '/swift-rate-app': typeof SwiftRateAppRoute
  '/tulip-app': typeof TulipAppRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/atm-card'
    | '/heikenma-solar'
    | '/illustration'
    | '/laurienla-cake'
    | '/little-luminaries'
    | '/profile'
    | '/swift-rate-app'
    | '/tulip-app'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/atm-card'
    | '/heikenma-solar'
    | '/illustration'
    | '/laurienla-cake'
    | '/little-luminaries'
    | '/profile'
    | '/swift-rate-app'
    | '/tulip-app'
  id:
    | '__root__'
    | '/'
    | '/atm-card'
    | '/heikenma-solar'
    | '/illustration'
    | '/laurienla-cake'
    | '/little-luminaries'
    | '/profile'
    | '/swift-rate-app'
    | '/tulip-app'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AtmCardRoute: typeof AtmCardRoute
  HeikenmaSolarRoute: typeof HeikenmaSolarRoute
  IllustrationRoute: typeof IllustrationRoute
  LaurienlaCakeRoute: typeof LaurienlaCakeRoute
  LittleLuminariesRoute: typeof LittleLuminariesRoute
  ProfileRoute: typeof ProfileRoute
  SwiftRateAppRoute: typeof SwiftRateAppRoute
  TulipAppRoute: typeof TulipAppRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/tulip-app': {
      id: '/tulip-app'
      path: '/tulip-app'
      fullPath: '/tulip-app'
      preLoaderRoute: typeof TulipAppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/swift-rate-app': {
      id: '/swift-rate-app'
      path: '/swift-rate-app'
      fullPath: '/swift-rate-app'
      preLoaderRoute: typeof SwiftRateAppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile': {
      id: '/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof ProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/little-luminaries': {
      id: '/little-luminaries'
      path: '/little-luminaries'
      fullPath: '/little-luminaries'
      preLoaderRoute: typeof LittleLuminariesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/laurienla-cake': {
      id: '/laurienla-cake'
      path: '/laurienla-cake'
      fullPath: '/laurienla-cake'
      preLoaderRoute: typeof LaurienlaCakeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/illustration': {
      id: '/illustration'
      path: '/illustration'
      fullPath: '/illustration'
      preLoaderRoute: typeof IllustrationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/heikenma-solar': {
      id: '/heikenma-solar'
      path: '/heikenma-solar'
      fullPath: '/heikenma-solar'
      preLoaderRoute: typeof HeikenmaSolarRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/atm-card': {
      id: '/atm-card'
      path: '/atm-card'
      fullPath: '/atm-card'
      preLoaderRoute: typeof AtmCardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AtmCardRoute: AtmCardRoute,
  HeikenmaSolarRoute: HeikenmaSolarRoute,
  IllustrationRoute: IllustrationRoute,
  LaurienlaCakeRoute: LaurienlaCakeRoute,
  LittleLuminariesRoute: LittleLuminariesRoute,
  ProfileRoute: ProfileRoute,
  SwiftRateAppRoute: SwiftRateAppRoute,
  TulipAppRoute: TulipAppRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
